F

diff --git a/Jenkins_vSphere/Jenkinsfile b/Jenkins_vSphere/Jenkinsfile
--- a/Jenkins_vSphere/Jenkinsfile
+++ b/Jenkins_vSphere/Jenkinsfile
@@ -10,10 +10,9 @@ pipeline {
         ANSIBLE_VM_HOST = "172.20.10.135"
         ANSIBLE_VM_USER = "template"
 
-        // Paths
-        TERRAFORM_PATH = "C:\\Program Files\\Terraform\\terraform.exe"
-        OVFTOOL_PATH   = "C:\\newovf\\VMwareOVFTool\\ovftool.exe"
-        GITBASH_PATH   = "C:\\Program Files\\Git\\bin\\bash.exe"
+        // Paths in Ubuntu VM
+        TERRAFORM_PATH = "/usr/local/bin/terraform"
+        OVFTOOL_PATH   = "/usr/local/bin/ovftool/ovftool"
     }
 
     options {
@@ -32,18 +31,18 @@ pipeline {
 
         stage('Test OVF Tool') {
             steps {
-                bat """
+                sh """
                     echo === Testing OVF Tool Path ===
-                    "${OVFTOOL_PATH}" --version
+                    '${OVFTOOL_PATH}' --version
                 """
             }
         }
 
         stage('Test Terraform') {
             steps {
-                bat """
+                sh """
                     echo === Testing Terraform Path ===
-                    "${TERRAFORM_PATH}" version
+                    '${TERRAFORM_PATH}' version
                 """
             }
         }
@@ -51,21 +50,21 @@ pipeline {
         stage('Terraform Operations') {
             steps {
                 withCredentials([string(credentialsId: 'ESXI_PASSWORD', variable: 'TF_VAR_esxi_password')]) {
-                    bat """
+                    sh """
                         echo === Navigating to Terraform Root Directory ===
-                        cd Terraform_vSphere\\root
+                        cd ~/ESXI_Automation/Terraform_vSphere/root
 
                         echo === Initializing Terraform ===
-                        "${TERRAFORM_PATH}" init
+                        '${TERRAFORM_PATH}' init
 
                         echo === Validating Terraform Configuration ===
-                        "${TERRAFORM_PATH}" validate
+                        '${TERRAFORM_PATH}' validate
 
                         echo === Planning Terraform Changes ===
-                        "${TERRAFORM_PATH}" plan -var="esxi_hostname=%ESXI_HOST%" -var="esxi_username=%ESXI_USERNAME%" -var="esxi_password=%TF_VAR_esxi_password%" -var="clone_source_vm=templateVM"
+                        '${TERRAFORM_PATH}' plan -var="esxi_hostname=${ESXI_HOST}" -var="esxi_username=${ESXI_USERNAME}" -var="esxi_password=${TF_VAR_esxi_password}" -var="clone_source_vm=templateVM"
 
                         echo === Applying Terraform Changes ===
-                        "${TERRAFORM_PATH}" apply -auto-approve -var="esxi_hostname=%ESXI_HOST%" -var="esxi_username=%ESXI_USERNAME%" -var="esxi_password=%TF_VAR_esxi_password%" -var="clone_source_vm=templateVM"
+                        '${TERRAFORM_PATH}' apply -auto-approve -var="esxi_hostname=${ESXI_HOST}" -var="esxi_username=${ESXI_USERNAME}" -var="esxi_password=${TF_VAR_esxi_password}" -var="clone_source_vm=templateVM"
                     """
                 }
             }
@@ -73,26 +72,24 @@ pipeline {
 
         stage('Generate Ansible Inventory') {
             steps {
-                bat """
-                    "${GITBASH_PATH}" -c "
-                        set -e
-                        echo '=== Generating Terraform Output JSON ==='
-                        cd Terraform_vSphere/root
-                        '${TERRAFORM_PATH}' output -json vm_inventory > ../Ansible_vSphere/terraform-output.json
+                sh """
+                    set -e
+                    echo '=== Generating Terraform Output JSON ==='
+                    cd ~/ESXI_Automation/Terraform_vSphere/root
+                    '${TERRAFORM_PATH}' output -json vm_inventory > ../../Ansible_vSphere/terraform-output.json
 
-                        echo '=== Running Inventory Generation Script ==='
-                        cd ../Ansible_vSphere
-                        chmod +x generated_inventory.sh
-                        ./generated_inventory.sh
+                    echo '=== Running Inventory Generation Script ==='
+                    cd ~/ESXI_Automation/Ansible_vSphere
+                    chmod +x generated_inventory.sh
+                    ./generated_inventory.sh
 
-                        echo '=== Displaying Generated Inventory ==='
-                        if [ -f inventory.ini ]; then
-                            cat inventory.ini
-                        else
-                            echo 'ERROR: inventory.ini was not generated.'
-                            exit 1
-                        fi
-                    "
+                    echo '=== Displaying Generated Inventory ==='
+                    if [ -f inventory.ini ]; then
+                        cat inventory.ini
+                    else
+                        echo 'ERROR: inventory.ini was not generated.'
+                        exit 1
+                    fi
                 """
             }
             post {
@@ -108,30 +105,24 @@ pipeline {
                     usernamePassword(credentialsId: 'ANSIBLE_VM_CREDENTIALS', usernameVariable: 'ANSIBLE_USER', passwordVariable: 'ANSIBLE_PASS'),
                     string(credentialsId: 'GRAFANA_ADMIN_PASSWORD', variable: 'GRAFANA_PASS')
                 ]) {
-                    bat """
-                        "${GITBASH_PATH}" -c "
+                    sh """
+                        set -e
+                        echo '=== Copying Ansible Files to Ansible VM ==='
+                        scp -o StrictHostKeyChecking=no -r ~/ESXI_Automation/Ansible_vSphere/* ${ANSIBLE_USER}@${ANSIBLE_VM_HOST}:/tmp/ansible/
+
+                        echo '=== Executing Ansible Playbooks on Ansible VM ==='
+                        ssh -o StrictHostKeyChecking=no ${ANSIBLE_USER}@${ANSIBLE_VM_HOST} \\
+                        "
                             set -e
-                            echo '=== Copying Ansible Files to Ansible VM ==='
-                            export ANSIBLE_VM_USER_TMP='%ANSIBLE_USER%'
-                            export ANSIBLE_VM_PASS_TMP='%ANSIBLE_PASS%'
-                            export GRAFANA_ADMIN_PASS_TMP='%GRAFANA_PASS%'
+                            mkdir -p ~/ansible_playbooks
+                            cp -r /tmp/ansible/* ~/ansible_playbooks/
+                            cd ~/ansible_playbooks
 
-                            scp -o StrictHostKeyChecking=no -r Ansible_vSphere/* %ANSIBLE_VM_USER_TMP%@%ANSIBLE_VM_HOST%:/tmp/ansible/
+                            echo '--- Running Basic Setup Playbook ---'
+                            ansible-playbook -i inventory.ini playbook-setup.yml
 
-                            echo '=== Executing Ansible Playbooks on Ansible VM ==='
-                            ssh -o StrictHostKeyChecking=no %ANSIBLE_VM_USER_TMP%@%ANSIBLE_VM_HOST% \"
-                                set -e
-                                echo '--- Setting up on Ansible VM ---'
-                                mkdir -p ~/ansible_playbooks
-                                cp -r /tmp/ansible/* ~/ansible_playbooks/
-                                cd ~/ansible_playbooks
-
-                                echo '--- Running Basic Setup Playbook ---'
-                                ansible-playbook -i inventory.ini playbook-setup.yml
-
-                                echo '--- Running Monitoring Setup Playbook ---'
-                                ansible-playbook -i inventory.ini playbook-monitor.yml -e grafana_admin_password=\\\$GRAFANA_ADMIN_PASS_TMP
-                            \"
+                            echo '--- Running Monitoring Setup Playbook ---'
+                            ansible-playbook -i inventory.ini playbook-monitor.yml -e grafana_admin_password=\\\$GRAFANA_PASS
                         "
                     """
                 }
