F

diff --git a/Jenkins_vSphere/Jenkinsfile b/Jenkins_vSphere/Jenkinsfile
--- a/Jenkins_vSphere/Jenkinsfile
+++ b/Jenkins_vSphere/Jenkinsfile
@@ -31,20 +31,6 @@ pipeline {
             }
         }
 
-        stage('Check Terraform Files') {
-            steps {
-                script {
-                    def tfDir = "${env.WORKSPACE}\\Terraform_vSphere"
-                    def tfFiles = new File(tfDir).listFiles().findAll { it.name.endsWith('.tf') }
-                    if (!tfFiles) {
-                        error "❌ No Terraform (.tf) files found in ${tfDir}! Pipeline stopped."
-                    } else {
-                        echo "✅ Terraform files found: ${tfFiles*.name}"
-                    }
-                }
-            }
-        }
-
         stage('Terraform Operations') {
             steps {
                 withCredentials([string(credentialsId: 'ESXI_PASSWORD', variable: 'TF_VAR_esxi_password')]) {
@@ -53,19 +39,19 @@ pipeline {
                         cd Terraform_vSphere
 
                         echo === Initializing Terraform ===
-                        \"${env.TERRAFORM_PATH}\" init
+                        "${env.TERRAFORM_PATH}" init
 
                         echo === Validating Terraform Configuration ===
-                        \"${env.TERRAFORM_PATH}\" validate
+                        "${env.TERRAFORM_PATH}" validate
 
                         echo === Planning Terraform Changes ===
-                        \"${env.TERRAFORM_PATH}\" plan ^
+                        "${env.TERRAFORM_PATH}" plan ^
                           -var="esxi_hostname=%ESXI_HOST%" ^
                           -var="esxi_username=%ESXI_USERNAME%" ^
                           -var="esxi_password=%TF_VAR_esxi_password%"
 
                         echo === Applying Terraform Changes ===
-                        \"${env.TERRAFORM_PATH}\" apply -auto-approve ^
+                        "${env.TERRAFORM_PATH}" apply -auto-approve ^
                           -var="esxi_hostname=%ESXI_HOST%" ^
                           -var="esxi_username=%ESXI_USERNAME%" ^
                           -var="esxi_password=%TF_VAR_esxi_password%"
@@ -76,24 +62,26 @@ pipeline {
 
         stage('Generate Ansible Inventory') {
             steps {
-                sh """
-                    set -e
-                    echo '=== Generating Terraform Output JSON ==='
-                    cd Terraform_vSphere
-                    '${env.TERRAFORM_PATH}' output -json vm_inventory > ../Ansible_vSphere/terraform-output.json
+                bat """
+                    "${env.GIT_BASH_PATH}" -c "
+                        set -e
+                        echo '=== Generating Terraform Output JSON ==='
+                        cd Terraform_vSphere
+                        '${env.TERRAFORM_PATH}' output -json vm_inventory > ../Ansible_vSphere/terraform-output.json
 
-                    echo '=== Running Inventory Generation Script ==='
-                    cd ../Ansible_vSphere
-                    chmod +x generated_inventory.sh
-                    ./generated_inventory.sh
+                        echo '=== Running Inventory Generation Script ==='
+                        cd ../Ansible_vSphere
+                        chmod +x generated_inventory.sh
+                        ./generated_inventory.sh
 
-                    echo '=== Displaying Generated Inventory ==='
-                    if [ -f inventory.ini ]; then
-                        cat inventory.ini
-                    else
-                        echo 'ERROR: inventory.ini was not generated.'
-                        exit 1
-                    fi
+                        echo '=== Displaying Generated Inventory ==='
+                        if [ -f inventory.ini ]; then
+                            cat inventory.ini
+                        else
+                            echo 'ERROR: inventory.ini was not generated.'
+                            exit 1
+                        fi
+                    "
                 """
             }
             post {
@@ -109,25 +97,31 @@ pipeline {
                     usernamePassword(credentialsId: 'ANSIBLE_VM_CREDENTIALS', usernameVariable: 'ANSIBLE_USER', passwordVariable: 'ANSIBLE_PASS'),
                     string(credentialsId: 'GRAFANA_ADMIN_PASSWORD', variable: 'GRAFANA_PASS')
                 ]) {
-                    sh """
-                        set -e
-                        echo '=== Copying Ansible Files to Ansible VM ==='
-                        scp -o StrictHostKeyChecking=no -r Ansible_vSphere/* ${ANSIBLE_USER}@${ANSIBLE_VM_HOST}:/tmp/ansible/
-
-                        echo '=== Executing Ansible Playbooks on Ansible VM ==='
-                        ssh -o StrictHostKeyChecking=no ${ANSIBLE_USER}@${ANSIBLE_VM_HOST} \\"
+                    bat """
+                        "${env.GIT_BASH_PATH}" -c "
                             set -e
-                            echo '--- Setting up on Ansible VM ---'
-                            mkdir -p ~/ansible_playbooks
-                            cp -r /tmp/ansible/* ~/ansible_playbooks/
-                            cd ~/ansible_playbooks
+                            echo '=== Copying Ansible Files to Ansible VM ==='
+                            export ANSIBLE_VM_USER_TMP='%ANSIBLE_USER%'
+                            export ANSIBLE_VM_PASS_TMP='%ANSIBLE_PASS%'
+                            export GRAFANA_ADMIN_PASS_TMP='%GRAFANA_PASS%'
 
-                            echo '--- Running Basic Setup Playbook ---'
-                            ansible-playbook -i inventory.ini playbook-setup.yml
+                            scp -o StrictHostKeyChecking=no -r Ansible_vSphere/* %ANSIBLE_VM_USER_TMP%@%ANSIBLE_VM_HOST%:/tmp/ansible/
 
-                            echo '--- Running Monitoring Setup Playbook ---'
-                            ansible-playbook -i inventory.ini playbook-monitor.yml -e grafana_admin_password=\\\$${GRAFANA_PASS}
-                        \\"
+                            echo '=== Executing Ansible Playbooks on Ansible VM ==='
+                            ssh -o StrictHostKeyChecking=no %ANSIBLE_VM_USER_TMP%@%ANSIBLE_VM_HOST% \\"
+                                set -e
+                                echo '--- Setting up on Ansible VM ---'
+                                mkdir -p ~/ansible_playbooks
+                                cp -r /tmp/ansible/* ~/ansible_playbooks/
+                                cd ~/ansible_playbooks
+
+                                echo '--- Running Basic Setup Playbook ---'
+                                ansible-playbook -i inventory.ini playbook-setup.yml
+
+                                echo '--- Running Monitoring Setup Playbook ---'
+                                ansible-playbook -i inventory.ini playbook-monitor.yml -e grafana_admin_password=\\\$GRAFANA_ADMIN_PASS_TMP
+                            \\"
+                        "
                     """
                 }
             }
